name: Renovate
on:
  workflow_dispatch:
  schedule:
  - cron: '0 */12 * * *'
jobs:
  renovate:
    runs-on: arc-runners #self-hosted
    env:
      RENOVATE_AUTODISCOVER: "true"
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@fdbe2b88946ea8b6fb5785a5267b46677d13a4d2 # v41.0.21
      with:
        configurationFile: renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}
