name: Renovate
on:
  workflow_dispatch:
  schedule:
  - cron: '0 */12 * * *'
jobs:
  renovate:
    runs-on: arc-runners #self-hosted
    env:
      RENOVATE_AUTODISCOVER: "true"
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@19e3d87179488d6a0cd9da744d37123ea4b338e5 # v41.0.20
      with:
        configurationFile: renovate.json
        token: ${{ secrets.RENOVATE_TOKEN }}
